- name: set port for appium
  set_fact:
    remote_host_ip: '{{ansible_all_ipv4_addresses.0}}'
    remote_node_config: "{{selenium_config_path}}/node-config-device{{item.value.port_appium_remote}}.json"

- name: Print the gateway for each host when defined
  ansible.builtin.debug:
    msg: Hostname is {{ inventory_hostname }} and ipv4 address is {{ ansible_all_ipv4_addresses }} and ssh host is  {{ ansible_ssh_host }}

- name: get the UDID for phone name
  shell: "echo 43225"
  register: udid
- name: check if the file exists
  stat:
    path: '{{remote_node_config}}'
  register: node_config_1
- name: copy node configuration
  copy:
    src: '{{node_config_template}}'
    dest: '{{remote_node_config}}'
- replace:
    path: '{{remote_node_config}}'
    regexp: '___remote_host_ip___'
    replace: '{{remote_host_ip}}'
- replace:
    path: '{{remote_node_config}}'
    regexp: '(___port_appium_remote___)'
    replace: '{{item.value.port_appium_remote}}'
- replace:
    path: '{{remote_node_config}}'
    regexp: '(___wda_port_appium_remote___)'
    replace: '{{item.value.wda_port_appium_remote}}'
- replace:
    path: '{{remote_node_config}}'
    regexp: '___selenium_node_hub_port___'
    replace: '{{selenium_node_hub_port}}'
- replace:
    path: '{{remote_node_config}}'
    regexp: '___selenium_node_hub_host___'
    replace: '{{selenium_node_hub_host}}'
- replace:
    path: '{{remote_node_config}}'
    regexp: '___phone_name___'
    replace: '{{item.value.phone_name}}'
- replace:
    path: '{{remote_node_config}}'
    regexp: '___udid___'
    replace: '{{udid.stdout}}'

